# Generated by Django 5.0.14 on 2026-10-03 08:42

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="در صورت خالی بودن، از عنوان اصلی استفاده می\u200cشود.",
                        max_length=70,
                        verbose_name="عنوان سئو",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="توضیحات متا"
                    ),
                ),
                (
                    "seo_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="تصویر اشتراک\u200cگذاری (OG)",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(max_length=300, verbose_name="توضیح کوتاه"),
                ),
                ("full_description", models.TextField(verbose_name="توضیح کامل")),
                (
                    "main_image",
                    models.ImageField(
                        upload_to="products/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="تصویر اصلی",
                    ),
                ),
                (
                    "order_cta_label",
                    models.CharField(
                        default="تماس بگیرید و سفارش دهید",
                        max_length=100,
                        verbose_name="متن دکمه سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
                "ordering": ["display_order", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان ویژگی")),
                ("description", models.TextField(blank=True, verbose_name="توضیح")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی محصول",
                "verbose_name_plural": "ویژگی\u200cهای محصول",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/gallery/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="متن جایگزین"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر محصول",
                "verbose_name_plural": "تصاویر محصول",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="شرکت / سازمان"
                    ),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="شماره تماس")),
                ("city", models.CharField(max_length=100, verbose_name="شهر")),
                (
                    "quantity",
                    models.CharField(
                        help_text="مثلاً ۲۰۰ متر",
                        max_length=100,
                        verbose_name="مقدار موردنیاز",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="نوع / مدل / رنگ"
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="محل یا کاربرد"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جدید"),
                            ("contacted", "تماس گرفته شد"),
                            ("done", "نهایی شد"),
                            ("cancelled", "لغو شد"),
                        ],
                        default="new",
                        max_length=12,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="یادداشت داخلی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش ریسه",
                "verbose_name_plural": "سفارش\u200cهای ریسه",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to="products/videos/",
                        validators=[apps.core.validators.validate_video_file],
                        verbose_name="فایل ویدیو",
                    ),
                ),
                (
                    "poster",
                    models.ImageField(
                        upload_to="products/videos/posters/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="پوستر",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="عنوان"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویدیوی محصول",
                "verbose_name_plural": "ویدیوهای محصول",
                "ordering": ["display_order"],
            },
        ),
    ]
