# Generated by Django 5.0.14 on 2026-10-03 08:42

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=120, unique=True, verbose_name="اسلاگ"
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی پروژه",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای پروژه",
                "ordering": ["display_order", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="در صورت خالی بودن، از عنوان اصلی استفاده می\u200cشود.",
                        max_length=70,
                        verbose_name="عنوان سئو",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="توضیحات متا"
                    ),
                ),
                (
                    "seo_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="تصویر اشتراک\u200cگذاری (OG)",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان پروژه")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=280, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(max_length=300, verbose_name="توضیح کوتاه"),
                ),
                (
                    "full_description",
                    models.TextField(verbose_name="توضیح کامل / داستان پروژه"),
                ),
                (
                    "design_concept",
                    models.TextField(blank=True, verbose_name="مفهوم طراحی"),
                ),
                (
                    "manufacturing_notes",
                    models.TextField(blank=True, verbose_name="ساخت و تولید"),
                ),
                (
                    "execution_notes",
                    models.TextField(blank=True, verbose_name="اجرا و نصب"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to="projects/covers/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="تصویر کاور",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="شهر"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="محل دقیق"
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="سال اجرا"
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="کارفرما"
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, verbose_name="پروژه ویژه (نمایش در صفحه اصلی)"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="projects.projectcategory",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروژه",
                "verbose_name_plural": "پروژه\u200cها",
                "ordering": ["display_order", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="projects/gallery/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="عنوان"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="زیرنویس"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="متن جایگزین (Alt)"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("design", "طراحی"),
                            ("build", "ساخت"),
                            ("install", "نصب و اجرا"),
                            ("result", "نتیجه\u200cی نهایی"),
                        ],
                        default="result",
                        help_text="عکس در کدام مرحله\u200cی پروژه گرفته شده؟ صفحه\u200cی پروژه بر همین اساس چیده می\u200cشود.",
                        max_length=10,
                        verbose_name="مرحله",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر پروژه",
                "verbose_name_plural": "تصاویر پروژه",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to="projects/videos/",
                        validators=[apps.core.validators.validate_video_file],
                        verbose_name="فایل ویدیو",
                    ),
                ),
                (
                    "poster",
                    models.ImageField(
                        upload_to="projects/videos/posters/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="پوستر",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="عنوان"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیح")),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="زیرنویس"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="projects.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویدیوی پروژه",
                "verbose_name_plural": "ویدیوهای پروژه",
                "ordering": ["display_order"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["slug"], name="projects_pr_slug_042165_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["featured", "published"], name="projects_pr_feature_8fef0f_idx"
            ),
        ),
    ]
