# Generated by Django 5.0.14 on 2026-10-03 08:42

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="در صورت خالی بودن، از عنوان اصلی استفاده می\u200cشود.",
                        max_length=70,
                        verbose_name="عنوان سئو",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="توضیحات متا"
                    ),
                ),
                (
                    "seo_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="تصویر اشتراک\u200cگذاری (OG)",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(max_length=300, verbose_name="توضیح کوتاه"),
                ),
                ("full_description", models.TextField(verbose_name="توضیح کامل")),
                (
                    "main_image",
                    models.ImageField(
                        upload_to="services/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="تصویر اصلی",
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمت",
                "verbose_name_plural": "خدمات",
                "ordering": ["display_order", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="services/gallery/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="متن جایگزین"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="services.service",
                        verbose_name="خدمت",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر خدمت",
                "verbose_name_plural": "تصاویر خدمت",
                "ordering": ["display_order"],
            },
        ),
    ]
