"""
Template filters that expose the WebP/thumbnail variants generated by
apps.core.image_pipeline (via the post_save signal in apps.core.signals)
to templates, with a safe fallback to the original file if a variant
hasn't been generated yet (e.g. media uploaded before this pipeline
existed, or a non-local storage backend where variant generation is
skipped — see apps/core/signals.py).
"""
import os

from django import template
from django.utils.html import format_html
from django.core.files.storage import default_storage

register = template.Library()


def _variant_url(image_field, suffix):
    if not image_field:
        return ""
    root, _ext = os.path.splitext(image_field.name)
    variant_name = f"{root}{suffix}.webp"
    if default_storage.exists(variant_name):
        return default_storage.url(variant_name)
    return image_field.url  # graceful fallback — never a broken <img>


@register.filter
def webp_thumb(image_field):
    return _variant_url(image_field, "-thumb")


@register.filter
def webp_medium(image_field):
    return _variant_url(image_field, "-medium")


@register.filter
def webp_full(image_field):
    return _variant_url(image_field, "")


@register.filter
def image_srcset(image_field):
    """
    Real srcset with ACCURATE width descriptors — read from each variant
    file's actual header via Pillow (cheap: Image.open() is lazy and does
    not decode pixel data just to read .size), never a guessed/hardcoded
    width. A wrong width descriptor is arguably worse than no srcset at
    all, since the browser trusts it to pick the "right" source.
    """
    if not image_field:
        return ""
    from PIL import Image

    entries = []
    for suffix in ("-thumb", "-medium", ""):
        root, _ext = os.path.splitext(image_field.name)
        variant_name = f"{root}{suffix}.webp"
        if not default_storage.exists(variant_name):
            continue
        try:
            with default_storage.open(variant_name, "rb") as f, Image.open(f) as img:
                width = img.width
        except Exception:
            continue
        entries.append(f"{default_storage.url(variant_name)} {width}w")

    return ", ".join(entries)


@register.simple_tag
def pic(field, alt="", sizes="100vw", eager=False, cls="", style=""):
    """
    One <img> with everything image-SEO and Core Web Vitals need: WebP source, real srcset (accurate widths),
    intrinsic width/height (no layout shift), lazy-loading (or fetchpriority=high for the LCP image), async decoding.
    Falls back to the original file when no variant exists, so it never renders a broken image.
    """
    if not field:
        return ""
    try:
        width, height = field.width, field.height
    except Exception:
        width = height = None
    attrs = [("src", _variant_url(field, ""))]
    srcset = image_srcset(field)
    if srcset:
        attrs += [("srcset", srcset), ("sizes", sizes)]
    attrs.append(("alt", alt or ""))
    if width and height:
        attrs += [("width", width), ("height", height)]
    if eager:
        attrs.append(("fetchpriority", "high"))
    else:
        attrs.append(("loading", "lazy"))
    attrs.append(("decoding", "async"))
    if cls:
        attrs.append(("class", cls))
    if style:
        attrs.append(("style", style))
    return format_html("<img {}>", format_html(" ".join(["{}=\"{}\""] * len(attrs)), *[x for kv in attrs for x in kv]))
