# Generated by Django 5.0.14 on 2026-10-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsultationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام")),
                ("phone", models.CharField(max_length=32, verbose_name="تلفن")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="شهر"),
                ),
                (
                    "project_type",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="نوع پروژه"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جدید"),
                            ("contacted", "تماس گرفته شده"),
                            ("in_progress", "در حال بررسی"),
                            ("completed", "تکمیل\u200cشده"),
                            ("archived", "بایگانی\u200cشده"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
            ],
            options={
                "verbose_name": "درخواست مشاوره",
                "verbose_name_plural": "درخواست\u200cهای مشاوره",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, verbose_name="تلفن"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جدید"),
                            ("contacted", "تماس گرفته شده"),
                            ("in_progress", "در حال بررسی"),
                            ("completed", "تکمیل\u200cشده"),
                            ("archived", "بایگانی\u200cشده"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
            ],
            options={
                "verbose_name": "پیام تماس",
                "verbose_name_plural": "پیام\u200cهای تماس",
                "ordering": ["-created_at"],
            },
        ),
    ]
