# Generated by Django 5.0.14 on 2026-10-03 08:42

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomepageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "هیرو"),
                            ("brand_intro", "معرفی برند"),
                            ("differentiator", "تفاوت پرتو نور"),
                            ("featured_projects", "پروژه\u200cهای منتخب"),
                            ("company_video", "ویدیوی معرفی شرکت"),
                            ("services", "خدمات"),
                            ("product_highlight", "محصول ویژه (ریسه نوری)"),
                            ("statistics", "آمار"),
                            ("workshop", "کارگاه/تیم"),
                            ("team", "تیم"),
                            ("gallery", "گالری"),
                            ("cta", "دعوت به اقدام"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="نوع بخش",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="عنوان"),
                ),
                (
                    "subtitle",
                    models.TextField(blank=True, verbose_name="زیرعنوان / توضیح"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="homepage/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="homepage/videos/",
                        validators=[apps.core.validators.validate_video_file],
                        verbose_name="ویدیو",
                    ),
                ),
                (
                    "video_poster",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="homepage/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="پوستر ویدیو",
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="متن دکمه"
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="آدرس دکمه"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, verbose_name="نمایش در صفحه اصلی"
                    ),
                ),
            ],
            options={
                "verbose_name": "بخش صفحه اصلی",
                "verbose_name_plural": "بخش\u200cهای صفحه اصلی",
                "ordering": ["display_order", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Navigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[("main", "منوی اصلی"), ("footer", "منوی فوتر")],
                        max_length=20,
                        unique=True,
                        verbose_name="محل نمایش",
                    ),
                ),
            ],
            options={
                "verbose_name": "منو",
                "verbose_name_plural": "منوها",
            },
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان مرحله")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="توضیح کوتاه (اختیاری)"
                    ),
                ),
            ],
            options={
                "verbose_name": "مرحله فرآیند همکاری",
                "verbose_name_plural": "مراحل فرآیند همکاری",
                "ordering": ["display_order", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name_fa",
                    models.CharField(
                        default="پرتو نور",
                        max_length=255,
                        verbose_name="نام شرکت (فارسی)",
                    ),
                ),
                (
                    "company_name_en",
                    models.CharField(
                        default="PARTO NOOR",
                        max_length=255,
                        verbose_name="نام شرکت (انگلیسی)",
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True,
                        default="طراحی، ساخت و اجرای المان\u200cهای نوری و نورپردازی شهری",
                        max_length=255,
                        verbose_name="شعار",
                    ),
                ),
                (
                    "logo_full",
                    models.ImageField(
                        upload_to="brand/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="لوگوی کامل",
                    ),
                ),
                (
                    "logo_symbol",
                    models.ImageField(
                        help_text="این نماد در فاویکون، هدر موبایل و صفحه بارگذاری استفاده می\u200cشود.",
                        upload_to="brand/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="نماد/آیکون برند",
                    ),
                ),
                (
                    "logo_light",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="brand/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="لوگو نسخه روشن",
                    ),
                ),
                (
                    "logo_dark",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="brand/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="لوگو نسخه تیره",
                    ),
                ),
                (
                    "favicon_ico",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="brand/",
                        validators=[apps.core.validators.validate_ico_file],
                        verbose_name="فاویکون (.ico)",
                    ),
                ),
                (
                    "favicon_svg",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="brand/",
                        validators=[apps.core.validators.validate_svg_file],
                        verbose_name="فاویکون (SVG)",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="تلفن ثابت"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="تلفن همراه"
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="شماره واتس\u200cاپ"
                    ),
                ),
                (
                    "whatsapp_enabled",
                    models.BooleanField(
                        default=False, verbose_name="نمایش دکمه واتس\u200cاپ"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس")),
                (
                    "map_embed_url",
                    models.URLField(blank=True, verbose_name="لینک نقشه (Embed)"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="اینستاگرام"),
                ),
                ("telegram_url", models.URLField(blank=True, verbose_name="تلگرام")),
                ("linkedin_url", models.URLField(blank=True, verbose_name="لینکدین")),
                ("aparat_url", models.URLField(blank=True, verbose_name="آپارات")),
                ("footer_text", models.TextField(blank=True, verbose_name="متن فوتر")),
                (
                    "copyright_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="متن کپی\u200cرایت"
                    ),
                ),
                (
                    "default_seo_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="عنوان پیش\u200cفرض سئو"
                    ),
                ),
                (
                    "default_seo_description",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="توضیحات پیش\u200cفرض سئو",
                    ),
                ),
                (
                    "default_og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="تصویر پیش\u200cفرض اشتراک\u200cگذاری",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("label", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "value",
                    models.CharField(
                        help_text="مثلا 120+ یا 8 سال",
                        max_length=50,
                        verbose_name="مقدار",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="آیکون (اختیاری)"
                    ),
                ),
            ],
            options={
                "verbose_name": "آمار",
                "verbose_name_plural": "آمارها",
                "ordering": ["display_order", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="مسیر داخلی (مثلا /projects/) یا آدرس کامل خارجی.",
                        max_length=255,
                        verbose_name="آدرس",
                    ),
                ),
                (
                    "is_external",
                    models.BooleanField(default=False, verbose_name="لینک خارجی"),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False, verbose_name="باز شدن در تب جدید"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "navigation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.navigation",
                        verbose_name="منو",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.navigationitem",
                        verbose_name="زیرمجموعه از",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم منو",
                "verbose_name_plural": "آیتم\u200cهای منو",
                "ordering": ["display_order"],
            },
        ),
    ]
