# Generated by Django 5.0.14 on 2026-10-04 08:06

from django.db import migrations, models


def clear_placeholder(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.filter(company_name_en="PARTO NOOR").update(company_name_en="")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_role_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="company_name_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="اختیاری؛ زیر نام فارسی در هدر نمایش داده می\u200cشود.",
                max_length=255,
                verbose_name="نام شرکت (انگلیسی)",
            ),
        ),
        migrations.RunPython(clear_placeholder, migrations.RunPython.noop),
    ]
