# Generated by Django 5.0.14 on 2026-10-04 14:21

import apps.core.validators
from django.db import migrations, models


CLIENT_PHONE = "09156249754"
CLIENT_INSTAGRAM = "https://www.instagram.com/partonoor.co/"


def merge_contact(apps, schema_editor):
    """Keep a single phone number (the one given by the client) before the unused contact fields are dropped."""
    SiteSettings = apps.get_model("core", "SiteSettings")
    if not SiteSettings.objects.exists():
        SiteSettings.objects.create(pk=1)
    for row in SiteSettings.objects.all():
        row.phone = row.mobile or row.phone or CLIENT_PHONE
        row.instagram_url = row.instagram_url or CLIENT_INSTAGRAM
        row.save(update_fields=["phone", "instagram_url"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sitesettings_english_name_optional"),
    ]

    operations = [
        migrations.RunPython(merge_contact, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="sitesettings",
            name="address",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="aparat_url",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="email",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="map_embed_url",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="telegram_url",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="whatsapp_enabled",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="whatsapp_number",
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="kicker",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="برچسب کوچک بالای عنوان"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="maintenance_message",
            field=models.TextField(
                blank=True,
                default="در حال انجام کارهای فنی و به\u200cروزرسانی هستیم و به\u200cزودی برمی\u200cگردیم. از شکیبایی شما سپاسگزاریم.",
                verbose_name="متن صفحه\u200cی تعمیرات",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="maintenance_mode",
            field=models.BooleanField(
                default=False,
                help_text="با فعال\u200cکردن آن، بازدیدکنندگان فقط «صفحه\u200cی تعمیرات» را می\u200cبینند. پنل مدیریت و مدیر واردشده سایت را عادی می\u200cبینند.",
                verbose_name="حالت تعمیرات فعال باشد",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="maintenance_title",
            field=models.CharField(
                blank=True,
                default="سایت در حال به\u200cروزرسانی است",
                max_length=150,
                verbose_name="عنوان صفحه\u200cی تعمیرات",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_telegram",
            field=models.BooleanField(
                default=True,
                help_text="پیوند تلگرام از همان «شماره تماس» ساخته می\u200cشود.",
                verbose_name="نمایش تلگرام",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_whatsapp",
            field=models.BooleanField(
                default=True,
                help_text="پیوند واتس\u200cاپ از همان «شماره تماس» ساخته می\u200cشود.",
                verbose_name="نمایش واتس\u200cاپ",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="instagram_url",
            field=models.URLField(
                blank=True,
                help_text="آدرس کامل صفحه، مثلاً https://www.instagram.com/نام_کاربری/",
                verbose_name="اینستاگرام",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_full",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="brand/",
                validators=[apps.core.validators.validate_image_file],
                verbose_name="لوگوی کامل",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_symbol",
            field=models.ImageField(
                blank=True,
                help_text="این نماد در فاویکون، هدر موبایل و صفحه بارگذاری استفاده می\u200cشود.",
                null=True,
                upload_to="brand/",
                validators=[apps.core.validators.validate_image_file],
                verbose_name="نماد/آیکون برند",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="مثال: 09151234567 — در هدر، فوتر، صفحه\u200cی تماس و دکمه\u200cی تماس موبایل نمایش داده می\u200cشود.",
                max_length=32,
                verbose_name="شماره تماس",
            ),
        ),
    ]
