# Generated by Django 5.0.14 on 2026-10-03 08:42

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("identity", "هویت شرکت"),
                            ("process", "فرآیند کار"),
                            ("capability", "توانمندی\u200cها"),
                        ],
                        max_length=20,
                        verbose_name="نوع بخش",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="عنوان"),
                ),
                ("content", models.TextField(blank=True, verbose_name="متن")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="about/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="about/videos/",
                        validators=[apps.core.validators.validate_video_file],
                        verbose_name="ویدیو",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
            ],
            options={
                "verbose_name": "بخش درباره ما",
                "verbose_name_plural": "بخش\u200cهای درباره ما",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام")),
                ("role", models.CharField(max_length=150, verbose_name="سمت")),
                (
                    "photo",
                    models.ImageField(
                        upload_to="team/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="عکس",
                    ),
                ),
                ("biography", models.TextField(blank=True, verbose_name="بیوگرافی")),
            ],
            options={
                "verbose_name": "عضو تیم",
                "verbose_name_plural": "اعضای تیم",
                "ordering": ["display_order", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkshopSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="عنوان"),
                ),
                ("content", models.TextField(blank=True, verbose_name="متن")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="workshop/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="workshop/videos/",
                        validators=[apps.core.validators.validate_video_file],
                        verbose_name="ویدیو",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
            ],
            options={
                "verbose_name": "بخش کارگاه",
                "verbose_name_plural": "بخش\u200cهای کارگاه",
                "ordering": ["display_order"],
            },
        ),
    ]
