# Generated by Django 5.0.14 on 2026-10-03 08:42

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=120, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی مقاله",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای مقاله",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=60, unique=True, verbose_name="عنوان"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=80, unique=True, verbose_name="اسلاگ"
                    ),
                ),
            ],
            options={
                "verbose_name": "برچسب",
                "verbose_name_plural": "برچسب\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="در صورت خالی بودن، از عنوان اصلی استفاده می\u200cشود.",
                        max_length=70,
                        verbose_name="عنوان سئو",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="توضیحات متا"
                    ),
                ),
                (
                    "seo_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="تصویر اشتراک\u200cگذاری (OG)",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=280, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                ("excerpt", models.CharField(max_length=300, verbose_name="خلاصه")),
                (
                    "content",
                    models.TextField(
                        help_text="محتوای HTML سالم\u200cسازی\u200cشده از ادیتور متن غنی.",
                        verbose_name="محتوا",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to="articles/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="تصویر کاور",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً: مرتضی اسفندیاری — مدیرعامل شرکت پرتونور",
                        max_length=200,
                        verbose_name="نام نویسنده و سمت",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="منتشر شده"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="articles.articlecategory",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="articles",
                        to="articles.tag",
                        verbose_name="برچسب\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="articles_ar_slug_452037_idx"),
                    models.Index(
                        fields=["published", "published_at"],
                        name="articles_ar_publish_4dfc89_idx",
                    ),
                ],
            },
        ),
    ]
