# Generated by Django 5.0.14 on 2026-10-03 08:42

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
            ],
            options={
                "verbose_name": "مجموعه گالری",
                "verbose_name_plural": "مجموعه\u200cهای گالری",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="WorkCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=170,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="توضیح کوتاه"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="نمایش در سایت"),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی آثار",
                "verbose_name_plural": "دسته\u200cبندی آثار",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "تصویر"), ("video", "ویدیو")],
                        default="image",
                        max_length=10,
                        verbose_name="نوع رسانه",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gallery/images/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="gallery/videos/",
                        validators=[apps.core.validators.validate_video_file],
                        verbose_name="ویدیو",
                    ),
                ),
                (
                    "video_poster",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gallery/videos/posters/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="پوستر ویدیو",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عنوان اثر"
                    ),
                ),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False,
                        help_text="اگر از دسته\u200cی این عکس مطمئن نیستید، تیک بزنید؛ تا تأیید نهایی در سایت نمایش داده نمی\u200cشود.",
                        verbose_name="در انتظار تأیید",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="زیرنویس"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="متن جایگزین"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="نمایش عمومی"),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="gallery.gallery",
                        verbose_name="مجموعه",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gallery_items",
                        to="projects.project",
                        verbose_name="پروژه مرتبط",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="اثر در بخش «آثار» زیر همین دسته نمایش داده می\u200cشود.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="gallery.workcategory",
                        verbose_name="دسته\u200cبندی اثر",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم گالری",
                "verbose_name_plural": "آیتم\u200cهای گالری",
                "ordering": ["display_order"],
            },
        ),
    ]
