# Generated by Django 5.0.14 on 2026-10-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workcategory",
            name="seo_description",
            field=models.CharField(
                blank=True,
                help_text="اختیاری؛ اگر خالی باشد از «توضیح کوتاه» ساخته می\u200cشود.",
                max_length=160,
                verbose_name="توضیحات متا",
            ),
        ),
        migrations.AddField(
            model_name="workcategory",
            name="seo_title",
            field=models.CharField(
                blank=True,
                help_text="اختیاری؛ اگر خالی باشد از عنوان دسته ساخته می\u200cشود.",
                max_length=70,
                verbose_name="عنوان سئو",
            ),
        ),
    ]
